### ISSUE TITLE
跟随M9A v1.0.0可能的修改方向

### ISSUE THREAD

**Issue by KaronGH** [MLAcookie/M9AWPF#7]
RT，M9A新的v1.0.0-beta3应该是把命令行界面暴露出来成interface.json了，测试了一下应该是可以直接根据读取的interface.json模拟terminal的输出结果，所以我的设想路线是：
1. 读取interface.json
2. 如果存在config文件（config/maa_pi_config.json）则读取里面的adb_path，address和resource（官服/B服），以及上次任务列表task
3. 备份config文件后临时移除config文件
4. 根据GUI的配置调用MaaPiCli.exe并模拟输入指令，然后执行

这样可以避免去构建Json，可以更好的自适应M9A可能的变动

**Comment by MLAcookie** [comment]
我看了下，新的改变有点出乎我的预料。这样的话还要写cli的输入逻辑，就感觉挺怪的。之前的话是检测到config就可以直接执行的，逻辑上就顺很多，ui界面就是用来方便生成config的。我先去看看有没有直接执行config的可能

**Comment by MLAcookie** [comment]
我想多了，生成config后启动就多输入个"6"来启动就好了

**Comment by KaronGH** [comment]
我的想法是，因为M9A是完全依靠interface.json生成命令行的，所以GUI也可以走一样的路径，也去解析interface.json，模拟命令行终端输入，让CLI自动生成config。这样无论interface.json作常规变动就不需要GUI进行附加更改了。后台解析interface.json和转化为CLI模拟输入的逻辑我写的差不多了，但我WPF这块不是很懂，不清楚如何对接到前端，这块还需要大佬多帮忙

**Comment by KaronGH** [comment]
周末写了两天序列化颇为痛苦，我觉得你这种思路也很不错，如果能根据现有的改改那就先用这个，新思路我可以慢慢实现

**Comment by MLAcookie** [comment]
1m188大佬的代码merge了，那么这个issue就先close了
